server:
  port: 2040
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    accesslog:
      encoding: UTF-8
    uri-encoding: UTF-8


spring:
  application:
    name: excutor
  devtools:
    restart:
      enabled: true
      additional-paths: src/mian/java
  #  eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2020/eureka/  #注册位置
  instance:
    instance-id: spring-cloud-server-2040

  #info 配置
info:
  app.name: 服务端
  app.author: dam

