server:
  port: 2030
  #  serverTimeZone=UTC&
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    accesslog:
      encoding: UTF-8
    uri-encoding: UTF-8
spring:
  application:
    name: javaServer
  datasource:
    username: root
    password: zhenlong
    url: jdbc:mysql://localhost:3306/jsoup?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
     multipart:
       max-file-size: 10MB
  devtools:
    restart:
      enabled: true
      additional-paths: src/mian/java

  #        邮箱配置
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: cytern@qq.com #发送邮件的邮箱地址
    password: qxqpanugbokcdiii #客户端授权码
    properties.mail.smtp.port: 465 #端口号
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

#mybatis 配置

mybatis:
  type-aliases-package: dam.jsoup.updatereport.updatereport.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#  eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2020/eureka/  #注册位置
  instance:
    instance-id: spring-cloud-server-2021

#info 配置
info:
  app.name: 脚本执行器
  app.author: dam
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 300000
#ribbon的超时时间
ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000


