server:
  port: 2030
  #  serverTimeZone=UTC&
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    accesslog:
      encoding: UTF-8
    uri-encoding: UTF-8
spring:
  jackson:
    time-zone: GMT+8
  cloud:
    config:
      enabled: false
  application:
    name: javaServer
  datasource:
    username: jsoup
    password: WsMDWjwyhxaMmDCd
    url: jdbc:mysql://82.157.40.205:3306/jsoup?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 10MB
  devtools:
    restart:
      enabled: true
      additional-paths: src/mian/java
  redis:
    host: 82.157.40.205
    port: 16379
    timeout: 20000
    expire-time: 3600
    password: cytern2020

  #        邮箱配置
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: cytern@qq.com #发送邮件的邮箱地址
    password: thxwrjscreeddicb #客户端授权码
    properties.mail.smtp.port: 465 #端口号
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

#mybatis 配置

mybatis:
  type-aliases-package: dam.jsoup.updatereport.updatereport.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#  eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://82.157.40.205:2020/eureka/  #注册位置
  instance:
    instance-id: spring-cloud-server-2030
    prefer-ip-address: true
tencent:
  SecretId: AKIDgBSTIuIRLzOYS6VfZDclfJhrmSs2ye4F
  SecretKey: 3rPilZ7QUJtDI8i27wWqujJdihW6QUIr

#info 配置
info:
  app.name: 脚本执行器
  app.author: dam
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 300000
#ribbon的超时时间
ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000
task:
  pool:
    corePoolSize: 5 #设置核心线程数
    maxPoolSize: 20  #设置最大线程数
    keepAliveSeconds: 300 #设置线程活跃时间（秒）
    queueCapacity: 50 #设置队列容量

#其余配置
dam:
  serverIp: 82.157.40.205
  checkDateTime: 5



